#!/usr/bin/env bash

# Update package lists
sudo apt update -y

# Install Nginx
sudo apt install nginx -y

# Set up default Nginx configuration
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx
sudo service nginx restart

echo "Nginx configuration updated successfully."
