#!/usr/bin/env bash

# Set NGINX configuration file paths
NGINX_SITES_AVAILABLE="/etc/nginx/sites-available/default"
NGINX_SITES_ENABLED="/etc/nginx/sites-enabled/default"

# Create a symbolic link between NGINX configuration files
if [ ! -e "$NGINX_SITES_ENABLED" ]; then
	    sudo ln -s "$NGINX_SITES_AVAILABLE" "$NGINX_SITES_ENABLED"
	        echo "Symbolic link created: $NGINX_SITES_AVAILABLE -> $NGINX_SITES_ENABLED"
	else
		    echo "Symbolic link already exists: $NGINX_SITES_ENABLED"
fi

# Restart NGINX service to apply configuration changes
sudo service nginx restart
