#!/usr/bin/env bash
# Configures an Nginx server to listen to port 80

# Creates a symbolic link (-s option) between the Nginx configuration file
# and the sites enabled directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart

# Terminates the first Nginx process ID
kill "${pgrep 'nginx' | head -1}"
