#!/usr/bin/env bash
# This script displays "Best School" 10 times, and Hi

name="Best School"
count=1

while [ $count -le 10 ]; do
    if [ $count -eq 9 ]; then
        echo "$name"
        echo "Hi"
    else
        echo "$name"
    fi
    ((count++))
done
