#!/usr/bin/env bash

# Get active IPv4 addresses
active_ips=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Display active IPv4 addresses
echo "Active IPv4 addresses:"
echo "$active_ips"
