#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chown -R nginx:nginx /usr/share/nginx/
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo systemctl enable nginx
sudo -u nginx service nginx restart
